apiVersion: v1
kind: ConfigMap
metadata:
  name: mykubewatch
data:
  .mykubewatch.yaml: |
    handler:
      mattermost:
        url: "https://mattermost.arcusx.com/hooks/yfrhxcomdtntmcfz9u5ucih43a"
        channel: "connistestchannel"
        username: "k8s"
    filter:
      namespaces: [ "default", "" ]
