---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mykubewatch
data:
  .mykubewatch.yaml: |
    handler:
      mattermost:
        url: "<put your webhook here>"
        channel: "k8s"
        username: "k8s"
    filter:
      namespaces: [ "default", "" ]
      kinds: []
      names: []
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mykubewatch
rules:
  - apiGroups: [""]
    resources: ["pods", "replicationcontrollers", "services", "configmaps", "deployments"]
    verbs: ["get", "watch", "list"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mykubewatch
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: mykubewatch
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mykubewatch
subjects:
  - kind: ServiceAccount
    name: mykubewatch
    namespace: default
---
apiVersion: v1
kind: Pod
metadata:
  name: mykubewatch
  namespace: default
spec:
  serviceAccountName: mykubewatch
  containers:
    - image: cbuschka/mykubewatch:1.0.0
      imagePullPolicy: Always
      name: mykubewatch
  restartPolicy: Always